version: '2'
services:
  nginx:
    image: nginx:1.13.9
    restart: always
    links:
      - redis
      - php
    depends_on:
      - php
    volumes:
      - ./www/:/var/www/html/:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs/nginx/:/var/log/nginx/
    ports:
      - 80:80
      - 443:443

  php:
    image: wordpress:4.9.4-php7.0-fpm
    restart: always
    volumes:
      - ./www:/var/www/html
      - ./etc/php:/etc/php:ro
      - ./logs/php/:/var/log/php/
    depends_on:
      - db
    links:
      - redis
      - db
    environment:
      - WORDPRESS_DB_NAME=wpdb
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_PASSWORD=test


  db:
    image: mariadb
    restart: always
    volumes:
      - ./etc/mysql:/etc/mysql
      - ./mysql:/var/lib/mysql
      - ./logs/mysql/:/var/log/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=test

  redis:
    image: redis
    restart: always
    volumes:
      - ./logs/redis/:/var/log/redis/
